"""Ajout champ discount à Payment

Revision ID: f706cc0ea202
Revises: e37e6edd6554
Create Date: 2025-09-15 17:27:19.414359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f706cc0ea202'
down_revision: Union[str, Sequence[str], None] = 'e37e6edd6554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('description', sa.String(), nullable=True))
    op.add_column('menus', sa.Column('category', sa.String(), nullable=True))
    op.add_column('menus', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('payments', sa.Column('qr_path', sa.String(), nullable=True))
    #op.add_column('payments', sa.Column('discount', sa.Float(), nullable=True))
    op.create_index(op.f('ix_payments_transaction_code'), 'payments', ['transaction_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_code'), table_name='payments')
    op.drop_column('payments', 'discount')
    op.drop_column('payments', 'qr_path')
    op.drop_column('payments', 'is_used')
    op.drop_column('menus', 'image_url')
    op.drop_column('menus', 'category')
    op.drop_column('menus', 'description')
    # ### end Alembic commands ###
